name: Build and Push Docker Images

on:
  push:
    branches:
      - FOND-20-research-on-github-action-cicd-idental-foundation

env:
  PROJECT_ROOT: D:/Krishtopher/MyProjects/dentistry-foundation-blazor
  GCP_PROJECT_ID: sandbox-446907
  GCP_REPO: asia-south1-docker.pkg.dev/sandbox-446907/idental-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install ABP CLI
        run: dotnet tool install -g Volo.Abp.Cli --version 8.0.3

      - name: Add ABP CLI to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-south1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # ------------------------
      # 🔧 AuthServer Build
      # ------------------------
      - name: Publish AuthServer
        run: dotnet publish src/Foundation.AuthServer/Foundation.AuthServer.csproj -c Release -o src/Foundation.AuthServer/publish

      - name: Build AuthServer Docker image
        run: |
          docker build \
            --build-arg CERT_BASE64=${{ secrets.AUTH_CERT_BASE64 }} \
            -t ${{ env.GCP_REPO }}/foundation-authserver:latest \
            -f src/Foundation.AuthServer/Dockerfile \
            src/Foundation.AuthServer

      - name: Push AuthServer Docker image
        run: docker push ${{ env.GCP_REPO }}/foundation-authserver:latest

      # ------------------------
      # 🌐 HttpApi.Host Build
      # ------------------------
      - name: Publish HttpApi.Host
        run: dotnet publish src/Foundation.HttpApi.Host/Foundation.HttpApi.Host.csproj -c Release -o src/Foundation.HttpApi.Host/publish

      - name: Build HttpApi.Host Docker image
        run: |
          docker build \
            -t ${{ env.GCP_REPO }}/foundation-httpapihost:latest \
            -f src/Foundation.HttpApi.Host/Dockerfile \
            src/Foundation.HttpApi.Host

      - name: Push HttpApi.Host Docker image
        run: docker push ${{ env.GCP_REPO }}/foundation-httpapihost:latest

      # ------------------------
      # 🖥️ Blazor Build
      # ------------------------
      - name: Publish Blazor
        run: dotnet publish src/Foundation.Blazor/Foundation.Blazor.csproj -c Release -o src/Foundation.Blazor/publish

      - name: Build Blazor Docker image
        run: |
          docker build \
            -t ${{ env.GCP_REPO }}/foundation-blazor:latest \
            -f src/Foundation.Blazor/Dockerfile \
            src/Foundation.Blazor

      - name: Push Blazor Docker image
        run: docker push ${{ env.GCP_REPO }}/foundation-blazor:latest
